name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
      - name: Run OpenApi Generate for Java
        run: ./gradlew openApiGenerate
      - name: Run OpenApi Generate for TS
        run: ./gradlew npmInstall && cd ./plyushkin-web-ui && bash ./generate-ts-http-client.sh
      - name: Build TS project
        run: ./gradlew :plyushkin-web-ui:build